### ISSUE TITLE
Built on Windows, Run on Windows??

### ISSUE THREAD

**Issue by sgoveia** [ruckstack/ruckstack#34]
Amazing project...!
Like the title, if I build the installer on Windows, can I run the server on Windows? I know k3s can run on Windows.
Thanks!

**Comment by nvoxland** [comment]
Currently the server just runs on Linux because as far as I could tell, k3s required Linux. 

https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/ just says "K3s should run on just about any flavor of Linux." with no mention of Windows. In my quick testing, I was even having a hard time getting it to run under WSL2.

Do you have any info on what it takes to run on k3s on Windows? It would be great to be able to.

**Comment by sgoveia** [comment]
Thanks for the reply! This is all I could find
https://github.com/rancher/k3s/issues/114

**Comment by nvoxland** [comment]
That's about all I could find too. Once they add windows support, I'll be sure to add it. Hopefully it happens
