### ISSUE TITLE
Deliver builder via docker container

### ISSUE THREAD

**Issue by nvoxland** [ruckstack/ruckstack#37]
**LOOKING FOR FEEDBACK ON THIS IDEA**

I'm wondering about replacing the linux/windows zip/tgz downloads of the builder with focusing on just supporting a docker container. 

**Pros:**
- Don't have to worry about cross-platform support
- Don't have to worry about external libraries/processes being installed
- Makes user buildserver setup exactly the same as local setup
- Built-in upgrade distribution setup (docker pull)
- ???

**Cons:**
- More complex client install (needs Docker or Containerd or something to run the container)
- Longer CLI command (can still ship a wrapper script to mitigate)
- ???

**Comment by nvoxland** [comment]
I've been working on a docker version in PR #38 . It is working, but has some possible drawbacks so I'm still unsure if I should pull it out or leave it in.

The way it is working, is that:
- The ruckstack CLI and all its resources are bundled into a published docker image
- That docker image can be used like any other docker image
- But, I also created a "ruckstack launcher" CLI which is something you can put on your machine like any other executable and it wraps the docker execution behind something that looks like a regular CLI
- The launcher takes the arguments you give it, pulls & runs the docker image, adjusting any arguments as needed (--out and --project go to /data/out and /data/project with volume mounts created based on the actual directories passed)

So the view as a user is:
1. Download ruckstack.exe (or whatever platform you want)
2. Run ruckstack build --project /path/to/project --out -/path/to/out
3. Have your new project

The fact that it is using docker is transparent to the user, except:
1. #2 fails if docker is not installed (it would normally, since it needs docker to build)
2. #2 fails if the ruckstack docker image is not in the local cache and you don't have network access
3. Your project in #3 has the files owned by your user, but group "docker"

I like that the file you download for #1 is just a single file with nothing else to install or files to manage. Installation is super easy. 
But, the security mapping is a bit odd and the volume mapping is a bit tricky to mange. 

That "dockerize" branch is under heavy general refactoring, making many, many other changes so it is currently broken in general. 

But, I'm deciding if I want to undo the docker part of that branch or keep it in there.

**Comment by jameswmcnab** [comment]
I'm sort of torn on this.

On the one had, I think the idea of providing an official Docker image that contains all the build tooling required to build a Ruckstack installer makes a lot of sense, as it does remove the need for maintaining builds for multiple platforms. It also allows for easier iteration and evolution of the internals (e.g. #36).

At the moment Docker is required for building anyway, so it doesn't add a new dependency there. Potential Ruckstack users are almost certain to have and be familiar with Docker anyway, considering what Ruckstack is and how it works requires some level of experience with containers and K8s.

On the other hand I don't know of any other tool that is *only* packaged as a Docker image. Not sure if this matters but there could be a reason for that I'm not aware of.

While writing this I've realised that if you do go down this road I'm not sure you even need the launcher executable. User should be happy with using the Docker CLI to run images, mount volumes etc; so running the image directly doesn't seem like it would be too bad for the developer experience? A simple shell wrapper or alias could provide a shorthand if required. One of the goals is to avoid having to maintain builds for different platforms, so that would tally quite well.

I noticed you added a mac build here, however `BUILD.sh` `test` function runs the linux binary so I get a `./BUILD.sh: line 53: out/artifacts/linux/ruckstack: cannot execute binary file` error on MacOS. Swapping that out for the mac binary I get a `Error launching Ruckstack:cannot find docker group: group: unknown group docker` error instead. I assume this due to how Docker Desktop for Mac works vs. Docker natively on Linux.

**Comment by nvoxland** [comment]
Thanks for the feedback. I'm still a bit torn on it too. I can't think of any other tools that are only packaged as a docker image either. Maybe I'm just visionary??? :) 

I started the launcher as a shell wrapper, but quickly decided that Go's cross-platform compiling was much nicer than dealing with bash differences and whatever we'd have to do for windows. It's still very lightweight

As I'm pushing towards a 1.0 release, I'm leaning toward the odd, docker-only approach for the development speed. If I can avoid implementing rpm, deb, msi, and dmg files that gets us to a stable, GA release sooner. Then, I can collect some real-user feedback and can always switch back to a traditional installation system in a future release.

Thanks for the heads-up on the mac side. I'm rewriting a large swath of the code in that branch and focusing on linux first since I'm stuck with that dev environment for the server component. I tried and earlier iteration (before I added the docker group check) on a mac and it worked. I'm thinking that both mac and windows will need a different user mapping setup in the launcher. 

I'll get to that after I finish more of the refactoring. I'm currently changing how the files are stored on the installed server to reduce disk usage and also provide a way for incremental upgrade files. Until that's done, it's overall broken even for Linux...

**Comment by jameswmcnab** [comment]
I think considering the requirements of shipping not only a the executable but also all of the installer assets etc, the docker image approach does make a lot more sense. I certainly don't think you want to get caught up in maintaining rpm/deb etc releases.

I'm still not completely sold on the launcher, seems a bit too 'magic' for my liking especially as it's spinning up container with access to the Docker engine socket. At least with a shell script someone with no Go knowledge can review it and decide if they want to use or manually invoke the image in a similar way. I guess as long as it is explained the user that is what is going on - with instructions on how to run the image without using the launcher - then it doesn't do any harm.

**Comment by nvoxland** [comment]
I'm going to give the "always docker" route a try and see what the feedback is. It makes things easier for me, which makes things better for everyone.

If anyone run into problems with the overall concept, feel free to comment on this issue.
