### ISSUE TITLE
Support JSON formatted project files

### ISSUE THREAD

**Issue by nvoxland** [ruckstack/ruckstack#51]
Because some people prefer it

**Comment by nvoxland** [comment]
Waiting for feedback on whether people really care enough to need to support both formats, or if just yaml is fine. 

Upvote this issue if you would find json support useful

**Comment by jameswmcnab** [comment]
I think YAML is going to be the best bet here considering it is the de-facto config language for tooling in the container ecosystem.

I use JSON config files every day and I don't think its well suited for _human editable_ configuration due to low signal to noise ratio, lack of comments and no multi-line support.

**Comment by nvoxland** [comment]
Closing this as "won't do". If anyone disagrees, please comment.
